language: csharp
solution: snowflake-connector-net.sln
before_install: 
  - openssl aes-256-cbc -K $encrypted_69a05fb7394f_key -iv $encrypted_69a05fb7394f_iv -in Snowflake.Data.Tests/parameters.json.enc -out Snowflake.Data.Tests/parameters.json -d
install:
  - nuget restore snowflake-connector-net.sln
script:
  - xbuild /p:Configuration=Release snowflake-connector-net.sln
  - mono ./packages/OpenCover.4.6.519/tools/OpenCover.Console.exe -target:./packages/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe -targetargs:./Snowflake.Data.Tests/bin/Debug/Snowflake.Data.Tests.dll -register:user -filter:+[Snowflake.Data]Snowflake.Data.* -output:./CodeCov.xml
