configuration: Release 
platform: Any CPU

environment:
  my_secret:
    secure: wCQetQvPT4ZLs/RkRfze5yPhzstxdyBV/G8EoptCL8Y=
 
install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt Snowflake.Data.Tests\parameters.json.enc -secret %my_secret%
  
before_build:
  - nuget restore

build:
  parallel: true
  project: snowflake-connector-net.sln
  
      
test_script:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:".\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -returntargetcode -targetargs:".\Snowflake.Data.Tests\bin\Release\Snowflake.Data.Tests.dll" -register:user -filter:"+[Snowflake.Data]*" -output:"coverage.xml"      

after_test:
 - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
 - pip install codecov
 - codecov -f "coverage.xml" -t ffc6a21d-8176-4849-9047-e3a631dcd35a      

artifacts:
  - path: 'Snowflake.Data.Tests\bin\${configuration}\*.log'      
